### ISSUE TITLE
Installation problem on Ubuntu 16.04.LTS

### ISSUE THREAD

**Issue by siupenyau** [mw55309/poRe_docs#3]
Hi Thank you for sharing poRe.

I have tried to install poRe 0.24 on both Windows 7 and Ubuntu 16.04.LTS. The installation of poRe to Win is successful but I have encountered problem in installation to Ubuntu.

After I typed the command 'sudo R CMD install poRe_0.24.tar.gz', it returns 'install: missing destination file operand after 'poRe_0.24.tar.gz'. Do I miss the directly after 'poRe_0.24.tar.gz'?

On the other hand, would you please provide how to open and operate poRe on Ubuntu and Windows? Thank you in advance.

**Comment by mw55309** [comment]
Hello!

The command is:

R CMD INSTALL (capital letters)

"install" (lowercase) is a linux command that requires two arguments, hence the error

So try

```sh
R CMD INSTALL poRe_0.24.tar.gz
```

cheers
Mick
